### ISSUE TITLE
[improvement] Support `/var/local/cache` for `$CFG->localcachedir`

### ISSUE THREAD

**Issue by ceefour** [bitnami/bitnami-docker-moodle#101]
**Description**

When using Moodle with [Server cluster](https://docs.moodle.org/37/en/Server_cluster) configuration, it is recommended to:

> $CFG->localcachedir

> The difference from $CFG->cachedir is that the directory **does not have to be shared by all cluster nodes**, the file contents do not change. **Use local fast filesystem on each cluster node.**

However this is not yet easily configurable because no folder with proper permission is ready.

**Describe the results you expected:**

I propose adding this:

```docker
# Prepare /var/local/cache
RUN mkdir -vp /var/local/cache && \
    chown -Rc bitnami:daemon /var/local/cache && \
    chmod ug+rwx /var/local/cache
```

then setting as default in Moodle's `config.php`:

```php
$CFG->localcachedir = '/var/local/cache';
```

This should have little effect on a standalone instance, but will be helpful for cluster configuration, one less thing to configure. Of course admin still free to change `$CFG->localcachedir` to anything else after installation.

Related to #100.

**Comment by javsalgar** [comment]
Hi,

I think the change makes sense. We will consider it for future releases of the application. Thank you very much for the contribution :)

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.

**Comment by miguelurtado** [comment]
I like this.
