### ISSUE TITLE
The cron.php maintenance script has not been run for at least 24 hours.

### ISSUE THREAD

**Issue by ASAMedia** [bitnami/bitnami-docker-moodle#119]
**Description**
The Moodle admin interface under site administration -> Notifications reports that the cron.php has not run in the last 24h.
When I run the cron.php over the webinterface manually it works.

It is just a clean docker installation.

It seams like the cron is not auto scheduled in the container.

**Comment by marcosbc** [comment]
Hi, let me check this further and get back to you. The Moodle container does run Cron so it is possible the cron entry is not properly executed.

**Comment by marcosbc** [comment]
Hi, I've not been able to reproduce this issue in the current Moodle container. We're using the tag ``.

We recommend you check that the file `/etc/cron.d/moodle` exists and contains the line shown below:
```console
$ cat /etc/cron.d/moodle
*/1 * * * * bitnami sudo su daemon -s /bin/sh -c "/opt/bitnami/php/bin/php /opt/bitnami/moodle/admin/cli/cron.php > /dev/null"
```

Also check that cron is running:

```
$ ps aux | grep cron
root         76  0.0  0.0   8508  1656 ?        Ss   14:26   0:00 /usr/sbin/cron
```

You can test that the file is being executed with this:

```console
$ sed -i 's|> /dev/null|>> /tmp/myfile|' /etc/cron.d/moodle
```

And after some minutes the file should show some contents:

```
$ cat /tmp/myfile
Server Time: Wed, 27 May 2020 15:40:02 +0100


Execute scheduled task: Synchronise manual enrolments task (enrol_manual\task\sync_enrolments)
... started 15:40:02. Current memory use 15.4MB.
Verifying manual enrolment expiration...
...manual enrolment updates finished.
... used 0 dbqueries
... used 0.015249013900757 seconds
Scheduled task complete: Synchronise manual enrolments task (enrol_manual\task\sync_enrolments)
(...)
```

> NOTE: Don't forget to revert the change:
> ```
> $ sed -i 's|>> /tmp/myfile|> /dev/null|' /etc/cron.d/moodle

**Comment by ASAMedia** [comment]
Hi @marcosbc ,
I've cheked everything and used the container mentioned.
The `/etc/cron.d/moodle` is correct.
`ps aux | grep cron` returned the following line:
`root          73  0.0  0.0   8808  2012 ?        Ss   17:19   0:00 /usr/sbin/cron`

Then I activated the log output in  `/etc/cron.d/moodle`, but the myfile is after 1h still missing.
For better reproduction on this issue I append my `docker-compose.yml`
'''
version: '3.3'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    restart: always
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/home/default/moodle/mariadb:/bitnami/mariadb'
  moodle:
    build: ./moodle_custom
    restart: always
    environment:
      - LC_TIME=de_DE
      - TZ=Germany/Berlin
      - MOODLE_SITENAME=*******************
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - SMTP_HOST=*******************
      - SMTP_PORT=*******************
      - SMTP_USER=*******************
      - SMTP_PASSWORD=*******************
      - SMTP_PROTOCOL=tls
    ports:
      - '3020:80'
       - '3021:443'
    volumes:
      - '/home/default/moodle:/bitnami'
      - '/home/default/moodle/locale.gen:/etc/locale.gen'
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local

'''

**Comment by marcosbc** [comment]
@ASAMedia In principle the configuration of the docker-compose looks wrong, however, could you describe this?

```
build: ./moodle_custom
```

At least what it changes. Could you check on a different docker-compose using bitnami/moodle:latest if it works? Maybe it could be related to your custom container and some changes included there.

**Comment by ASAMedia** [comment]
Hi @marcosbc ,
as mentioned here #120 I created my own Dockerfile, wich uses the current `bitnami/moodle:latest` container to switch the system language. When I use the original docker-compose the issue is still there. 

The following **Quickfix** worked for me:
I called `sudo crontab -e` on the host and added the following line:
```
*/5 * * * * /usr/bin/docker-compose -f /home/default/moodle/docker-compose.yml exec -T moodle php /bitnami/moodle/admin/cli/cron.php >/dev/null 2>&1
```
This calls the cron.php every 5min.
Would be nice tho if the container does it on its own.

**Comment by marcosbc** [comment]
We tried the last Moodle container and it did run the cron job without any issues. When we modified the cron entry to write to a file, it did so each minute.

Therefore, I think there's something else happening with your install, but without the specific image we cannot test it.

In any case, I'm glad you were able to workaround it. The option is valid since at the end it runs cron, but obviously the ideal case would be for the container itself to run Cron. But like mentioned before, there's something else going on that we don't know what is, and unfortunately I don't know what else could be happening.

Has long time passed since you restarted your container? I'm thinking that the cron process itself could be stuck somehow, but I'm unsure on how to check for that.

**Comment by ASAMedia** [comment]
Hey @marcosbc,
I found a fix on the issue.
First I removed the changed the entry in `/etc/cron.d/moodle` to:
```
*/1 * * * * sudo su daemon -s /bin/sh -c "/opt/bitnami/php/bin/php /opt/bitnami/moodle/admin/cli/cron.php" > /dev/null 2>&1
```
I run `sudo crontab /etc/cron.d/moodle` in the container to add the entry to the main cron file and now everything works fine.
Looks like cron daily is not running the `/etc/cron.d/moodle` file

**Comment by marcosbc** [comment]
Thanks for letting us know. Still I'm unsure why you're getting these issues, they work for us.

> First I changed the entry in /etc/cron.d/moodle to:

Note that files in `cron.d` need to have the `user` field. See more: https://unix.stackexchange.com/questions/458713/how-are-files-under-etc-cron-d-used

> Looks like cron daily is not running the /etc/cron.d/moodle file

I've just created a clean Minideb environment where this works perfectly without having to run the command you mentioned. To do that, I entered a Bash console in the Minideb container (`docker run -ti bitnami/minideb bash`) and ran the following commands:

```console
$ install_packages sudo cron procps
$ useradd bitnami
$ cat <<< 'bitnami ALL=NOPASSWD: ALL' >> /etc/sudoers
$ cat <<< '*/1 * * * * bitnami sudo su daemon -s /bin/sh -c "echo bar >> /tmp/foo"' > /etc/cron.d/moodle
$ cron
```

Then, after about a minute, I could see the `/tmp/foo` file containing the expected `bar` text:

```console
$ cat /tmp/foo
bar
```

After even more time has passed, i.e. 2 minutes:

```
$ cat /tmp/bar
foo
foo
```

And that is exactly what the Bitnami Moodle container does, and like I mentioned it worked for us so I'm really unsure what could be going on on your side rather than using an old Bitnami Moodle container release. We were using the latest release tag `3.8.3-debian-10-r27`.
