### ISSUE TITLE
Moodle calendar is not changing language

### ISSUE THREAD

**Issue by ASAMedia** [bitnami/bitnami-docker-moodle#120]
**Description**

I installed moodle with docker-compose and added a German language pack.
The Calendar however still displays english months and timestamps

**Steps to reproduce the issue:**

1. setup moodle with docker-compose
2. add a non english language pack
3. check calendar for wrong strings

**Describe the results you received:**

![grafik](https://user-images.githubusercontent.com/41484117/82758775-df25ee80-9de8-11ea-8b1d-3ebeb63a0bc9.png)
![grafik](https://user-images.githubusercontent.com/41484117/82758782-eb11b080-9de8-11ea-8002-89c0a182581d.png)

**Describe the results you expected:**
I expected all values to be in the preferred language.

**Comment by carrodher** [comment]
Hi, I was trying to reproduce the issue but I can see all the buttons using the new language:

![Screenshot 2020-05-25 at 11 16 51](https://user-images.githubusercontent.com/13216600/82798763-468b7f00-9e79-11ea-8672-e5c474d90798.png)

Maybe it's an issue with the specific language pack you used. In my case, I tested with "Deutsch ‎(de)‎" (above screenshot) and also "Español - Internacional ‎(es)‎" and everything seems to be migrated to the selected language. Not sure if this issue can be related to the container itself, it seems something related to the specific package.

Can you see any error in your logs?

**Comment by ASAMedia** [comment]
Hi @carrodher ,
as you can see in your screenshot the timestamp of the date and the name of the month in the back  are still in english.
![grafik](https://user-images.githubusercontent.com/41484117/82831178-faabfa80-9eb7-11ea-8b87-fc1bd64ad825.png)

**Comment by carrodher** [comment]
Hi, yes you're right. After read a [couple of posts in the Moodle project itself](https://moodle.org/mod/forum/discuss.php?d=278639), it seems the Calendar and other sections use the translation from the system itself instead of the language pack, so you need to manually change the locales of your system (in this case the container).

We already have some documentation in the README about how to do it, please check [this section](https://github.com/bitnami/bitnami-docker-moodle#installing-additional-language-packs).

---------------------------------------------

Apart from that, in order to check that everything works as expected I installed the Spanish language pack, without any change in the container:
![Screenshot 2020-05-26 at 09 02 34](https://user-images.githubusercontent.com/13216600/82870741-c1fc3780-9f30-11ea-982f-754b94d8e346.png)
As you can see highlighted in red, there are some strings still in English, that it's the issue you rightly reported.

In order to solve the issue I added the following line to the `Dockerfile` in the `3/debian-10` folder of this repository:
```diff
 RUN echo 'en_AU.UTF-8 UTF-8' >> /etc/locale.gen && locale-gen
 RUN echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen && locale-gen
+RUN echo 'es_ES.UTF-8 UTF-8' >> /etc/locale.gen && locale-gen
 RUN ln -sf /dev/stdout /opt/bitnami/apache/logs/access_log && \
     ln -sf /dev/stderr /opt/bitnami/apache/logs/error_log
```

And changed the `docker-compose.yaml` present in the root directory in order to build the previously modified image:
```diff
     volumes:
       - 'mariadb_data:/bitnami'
   moodle:
-    image: 'bitnami/moodle:3'
+    build: 3/debian-10
     environment:
       - MARIADB_HOST=mariadb
       - MARIADB_PORT_NUMBER=3306
```
Now, after deploying the container and install the Spanish language pack, everything was translated:
![Screenshot 2020-05-26 at 09 06 27](https://user-images.githubusercontent.com/13216600/82871058-3c2cbc00-9f31-11ea-94f6-23d4d6ccb606.png)

In your case you should be able to do the same process but installing the local for your language instead of the Spanish one. In this example I am doing the changes in local, as suggested in the linked documentation, you can also build a new image using the `bitnami/moodle` as a base, there are different ways to customize/build a new image based on the existing one.

**Comment by ASAMedia** [comment]
Hi @carrodher,
I made a Dockerfile based on the existing one and added the lines you mentioned (for my own language). Now everything works as desired.
Thanks for your support.
