### ISSUE TITLE
wwwroot is not configurable

### ISSUE THREAD

**Issue by samueldmq** [bitnami/bitnami-docker-moodle#146]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Description**

wwwroot is an important config within moodle. There is no way to set it in the image, which configures 127.0.0.1
One of the effects is that users get an email with 127.0.0.1 as the moodle address when trying to reset their passwords.

**Steps to reproduce the issue:**

1. Install the instace and configure SMTP
2. As a user, ask for a reset

**Describe the results you received:**

As wwwroot is not properly configured, the email has a wrong address.

**Describe the results you expected:**

There should be a var to configure wwwroot.

**Version**

Latest.

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Installed via Bitnami Moodle Chart

**Comment by miguelaeh** [comment]
Hi @samueldmq ,
Thank you very much for reporting the issue. I have been able to reproduce it.
It seems we have the logic that configures it, but we don't have a way to provide the Moodle host to be set there.
I will create an internal task to work on this. However, we cannot provide an ETA for this, we will update the thread once we have news.
Regards.

**Comment by nguyenlamlll** [comment]
Hi @miguelaeh, if you don't have the time to implement it. May you provide some general guidance to start with (like, which files should I look at? - Because there are lots of scripts).

I encounter this issue as well. One is hosting Bitnami Moodle under the subpath. The other is configuring HTTPS for Moodle.
For the time being, I manually exec into the container and edit `bitnami/moodle/config.php`, add `$CFG->wwwroot = "https://mydomain.com"` to get it to work.

**Comment by miguelaeh** [comment]
Hi @nguyenlamlll ,
I took a fast look and the issue seems to be the missing host configuration into the `wwwroot`. You can see similar things at `libmoodle.sh`. We should add a new env var like `MOODLE_HOST` to the `moodle_env.sh` file to create that configuration

**Comment by psoares** [comment]
I just hit this issue by trying to deploy the bitnami moodle helm chart behind an istio virtual service. The istio ingress gateway is exposed as a service running on port 80, with a NLB in front of it on https (TLS termination is done at the NLB level). This results in most links in the page being broken:
![image](https://user-images.githubusercontent.com/192243/109192598-6bdd4e80-7765-11eb-98a7-a31ca949c8d8.png)

The first URL is https://myserver.com, but the links are http://myserver.com...

I tried injecting the HTTPS environment variable so try to influence the logic in /bitnami/moodle/config.php, but it didn't work.

**Comment by miguelaeh** [comment]
Hi guys, 
We didn't have the time to implement the changes yet, you should be able to workaround the issue by following this comment https://github.com/bitnami/bitnami-docker-moodle/issues/146#issuecomment-768896383

**Comment by MelonSmasher** [comment]
Would this also include the ability to serve moodle from a sub directory something like http://moodle.domain.com/moodle?

**Comment by miguelaeh** [comment]
Hi @MelonSmasher ,
Thank you for providing your workaround, I think that should be a different issue. Could you please open a new one for that?

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
