### ISSUE TITLE
Email notification uses 127.0.0.1 to generate URLs (for assests and links)

### ISSUE THREAD

**Issue by danieldiazastudillo** [bitnami/bitnami-docker-moodle#156]
**Description**

Emails are being sent with **localhost** (127.0.0.1) address instead of real HOST for links and assets URL source. This happens with some emails and notifications. For example in new forum message notification, the image it's being requested from **localhost** address:

![image](https://user-images.githubusercontent.com/14895873/100796724-dc433080-33ff-11eb-886a-2888bfc17321.png)

![image](https://user-images.githubusercontent.com/14895873/100796709-d2213200-33ff-11eb-96fd-880924d87a1a.png)

**Steps to reproduce the issue:**

1. Common _docker-compose_ configuration with persisted data.

**Describe the results you received:**

Another notification with this issue, it's the **Upload users** feature (when using the CSV file). All data it's being uploaded as expected, no issues in that part, but the generated URL it's again, localhost:

![image](https://user-images.githubusercontent.com/14895873/100797042-478d0280-3400-11eb-8cac-a5a3e96e1d87.png)

**This  doesn't happen when using the single Upload User feature, the generated URL it's correct**

**Describe the results you expected:**

All generated URLs (links and source URL for assets) to use the actual HOST. In some Moodle forums, the solution it's to change this line in `config.php`... (simple to edit beacause moodle-data it's being persisted)

``` php
if (empty($_SERVER['HTTP_HOST'])) {
  $_SERVER['HTTP_HOST'] = '127.0.0.1:8080';
}
```

...and change that address to the real HOST. Now, i don't know if this change may actually break how Moodle is running inside Docker. If i change that to `myhost.com`, do i have to specify the port? I know that Moodle inside Docker it's using `8080` so this is why i think this change may actually break something (or maybe not), my Moodle it's running perfectly besides this issue and i'm going to production tomorrow, so i can't risk a lot here.

**Comment by danieldiazastudillo** [comment]
This is another effect. The mailing list gets **127.0.0.1** so besides any configuration you made to the mail server configuration, Gmail and probably every email client will mark all mails from a Moodle running on Docker as SPAM.

![image](https://user-images.githubusercontent.com/14895873/100806935-246a4f00-3410-11eb-8be1-125584fd475e.png)

**Comment by rafariossaa** [comment]
Hi, 
  I launched one moodle and changed the hostname in the file, it did not seem to affect the navigation.
  In any case, you can run a new moodle container to do your tests and once it work you can do the needed changes in the production moodle. As a sugestion, always make a backup of the files before changing them.

**Comment by choma** [comment]
This is still an issue.
In my case, `config.php` file has:
```php
if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
  $CFG->wwwroot   = 'https://' . $_SERVER['HTTP_HOST'];
} else {
  $CFG->wwwroot   = 'http://' . $_SERVER['HTTP_HOST'];
}
```
Which, I guess, is generated [here](https://github.com/bitnami/bitnami-docker-moodle/blob/bb2cd6c412b3d9c13c3841cd04b3d44aed888b16/3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh#L326).

As suggested in [this moodle forum](https://moodle.org/mod/forum/discuss.php?d=395414#p1681464), the moodle docs recommends not using variables when setting `$CFG->wwwroot`.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for providing a detailed feedback on this issue.
  Could the cron be tricked to use `example.org` and set in the `/etc/hosts` that hostname to `127.0.0.1` ?.

**Comment by rafariossaa** [comment]
After asking other team's members, I am creating an internal task to be able to set the hostname. 
However I can not provide an ETA, we are a small team and this would depend on the workload, priorities, etc.
If you like to send a PR we will be glad to review and merge it.

**Comment by choma** [comment]
Hi,
Thank you for the quick reply.

> Could the cron be tricked to use `example.org` and set in the `/etc/hosts` that hostname to `127.0.0.1` ?.

I'm not sure I understand your proposal, I don't know moodle or the bitnami image well enough and I don't get how the cron jobs would be affected by the hosts file. Anyway, I did a quick test and it didn't work (maybe it's just an error from my part).

The easiest way to fix this problem is to set `wwwroot` to a fixed value, like:
```php
$CFG->wwwroot = 'mydomain.com';
```
I guesss it is also safer since, as recommended by [moodle docs](https://docs.moodle.org/310/en/Configuration_file#Setting_.24CFG-.3Ewwwroot_correctly), it doesn't use variables.

I just [asked a question in moodle](https://moodle.org/mod/forum/discuss.php?d=395414#p1685200) forums to better understand the docs recommendation on not using variables for `wwwroot`.

If you still want to use variables, I guess the best option would be to set the environment variables before running cron jobs. As a quick test, I modified `/etc/cron.d/moodle`, like this:
```
*/1 * * * * daemon export HTTP_HOST="mydomain.com" ; /opt/bitnami/php/bin/php /opt/bitnami/moodle/admin/cli/cron.php > /dev/null 2>> /bitnami/moodledata/moodle-cron.log
```
It works well (at least for this specific problem). Maybe it would be a good idea to use a script to load environment variables (like it is done with [php](https://github.com/bitnami/bitnami-docker-moodle/blob/b277274a7deb9200ea9f454d4ad39a86dde1b08c/3/debian-10/rootfs/opt/bitnami/scripts/php-env.sh), [apache](https://github.com/bitnami/bitnami-docker-moodle/blob/b277274a7deb9200ea9f454d4ad39a86dde1b08c/3/debian-10/rootfs/opt/bitnami/scripts/apache-env.sh), etc) before running cron jobs.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for sharing your findings, I am adding this information to our internal task.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
