### ISSUE TITLE
Support for PostgreSQL

### ISSUE THREAD

**Issue by lukecarr** [bitnami/bitnami-docker-moodle#157]
**Description**

Currently, MariaDB is the only database system supported by this image. Many sites, especially those that operate on large scales, opt to use PostgreSQL as the database provider over MariaDB/MySQL. It would be great if this image provided support for PostgreSQL alongside MariaDB.

**Comment by marcosbc** [comment]
Hi @lukecarr, currently it is not something we had envisioned to do in the short-term.

However, we recently open-sourced the initialization scripts in the [`rootfs` folder](https://github.com/bitnami/bitnami-docker-moodle/tree/master/3/debian-10/rootfs/opt/bitnami/scripts) of this repo. Relevant lines:

* [L70](https://github.com/bitnami/bitnami-docker-moodle/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh#L70)
* [L124](https://github.com/bitnami/bitnami-docker-moodle/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh#L124) and [L178](https://github.com/bitnami/bitnami-docker-moodle/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh#L178)
* [L138-L150](https://github.com/bitnami/bitnami-docker-moodle/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh#L138)

By updating those scripts then you should be able to get a working Moodle Docker image with PostgreSQL support. 

Note that you would also need to add postgresql-client to the Docker image for this to work properly:

```
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "postgresql-client" "11.10.0-0" --checksum ad9f4e750583d0f7b02afc119c3b505fc780c0c13407983a96f2923dc7e33c3e
```

We would be glad to review any related PR if you were able to implement such feature. Let us know if you would be up for it.

(Note: Unfortunately we have not yet implemented "postgresql-client-env.sh" not "libpostgresqlclient.sh", but it should not be needed if the SQL queries are left out for PostgreSQL DBs.)

**Comment by AlirezaHaghshenas** [comment]
Hello.
We plan to deploy Moodle to kubernetes and managed postgresql. We are ready to contribute connection to postgres.

Can someone please reopen this issue?

**Comment by rafariossaa** [comment]
Hi @AlirezaHaghshenas ,
  If you want to contribute to support postgresql connections, just create a PR and, if  you like, reference this issue.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
