### ISSUE TITLE
Installing Let's Encrypt certificate on Moodle

### ISSUE THREAD

**Issue by echondrok** [bitnami/bitnami-docker-moodle#160]
Hello

I would like to install a Let'sEncypt Certificate on my moodle server.

For starters, i've deployed a moodle instance using the bitnami-docker-moodle image in a fresh VM on Azure.

I've searched and found this (https://docs.bitnami.com/ibm/apps/gitlab/administration/generate-configure-certificate-letsencrypt/) documentation, but I'm a bit confused. 

Do i need to go in the docker container (with `docker exec -it moodle_moodle_1`) and perform the procedure described in the documentation or do i have to follow another procedure?

Thanks in advance for you help

**Comment by FraPazGal** [comment]
Hello @echondrok,

That guide should be valid assuming you are serving your moodle application publicly and have a domain name pointing to the public IP of your application. As you will need to root access to the console, please keep in mind that you may have to modify our docker image for this.

Nevertheless, I'll recommend you to use our svm solution [on Azure](https://bitnami.com/stack/moodle/cloud/azure) as it includes Let's Encypt by default.

**Comment by echondrok** [comment]
Hi @FraPazGal,

Thanks for the azure svm and HTTPS guide, but unfortunately I'm just using Azure to test the deployment process. The production deployment will be in another VM outside of Azure. 

I do have a domain name pointing to the public IP of my application. What changes exactly would the docker image need to have?

Is there a standard workflow that is being followed to add HTTTPS with Let's Encrypt using this docker image?

**Comment by marcosbc** [comment]
Hi @echondrok, that guide is meant for Bitnami cloud images and VMs, so it's probably not going to work well for containers.

In any case, with containers, the approach would involve creating the Let's Encrypt certificates outside of the containers and mounting them afterwards to the container image.

For instance, you could create the certificates in your Docker host, and then mount them as `/certs/server.crt` and `/certs/server.key` as described [here](https://github.com/bitnami/bitnami-docker-apache#using-custom-ssl-certificates). Since Let's Encrypt would create them via symlinks, it's probably easiest if you just copy them to another directory in your host for now.

For automatic renewals, you would need to copy them manually for now, although you should be able to create an automated job (i.e. with Cron) to update the certs and restart the Moodle container, or to "docker exec" into the container to reload Apache (i.e. "apachectl -k graceful").

**Comment by echondrok** [comment]
Thanks @marcosbc.
I made it work with your suggestion.
