### ISSUE TITLE
Support for memcached, Redis or external cache...

### ISSUE THREAD

**Issue by ernani** [bitnami/bitnami-docker-moodle#178]
Description

Currently, this image doesn't support external caches apparently. Many sites, especially those that operate on large scales, opt to use either Memcached or Redis as the cache provider for session/application. It would be great if this image provided support for external caches, such as a pod for Memcached, Redis or external cache (managed service).

**Comment by carrodher** [comment]
That's nice! I just added the `on-hold` label to prevent the stale bot closing the issue

**Comment by ernani** [comment]
I have created this issue in the moodle bitnami helm chart:
https://github.com/bitnami/charts/issues/6374

Using redis and memcached requires some additional modules which perhaps we can either add them or customize with flags on the original docker images to be added.

Is this something you guys would accept as a PR?

Cheers!

**Comment by ernani** [comment]
I did notice that some ini settings enablement is done in lib php script such as enabling opcache...

PHP is actually added as a file and then it gets unpacked...I have no way of knowing where to grab that data to unpack and my goal is to modify the default baseline docker image...

Considering that php's redis is installed with pecl and you guys do pack some distro of php, and redis.so is not in /opt/bitnami/php/lib/php/extensions, I think this might be done somewhere else.

Somehow, I am stuck on how to do it.

Sure I could add a pecl command in any of these scripts or inside of the Dockerfile but I am sure it is not where it is best suited to do so.

**Comment by carrodher** [comment]
You're right, although the container logic is 100% based on bash and available in this repository, the required components (such as PHP, Apache, MySQL, etc) are not easy to modify for external contributors since those packages are internally built.

In this case, it seems we will need to internally work on the task I created for this purpose (although it is going to depend on other priorities the team has so I can't provide an ETA). In the meantime, maybe you can extend/customize the image as described [here](https://github.com/bitnami/bitnami-docker-moodle#customize-this-image)

**Comment by ernani** [comment]
I appreciate it and I will wait for an ETA, the .so for both redis and perhaps mcrypt can then become a flag such as Opcache, right? This will be the most elegant way to change it IMHO.

I am trying to avoid having to maintain my own image as the bitnami's default has A LOT of gained benefits. This is an optimization that might benefit others too, and reduce the footprint on session storage as well as content caching, hence the proposal.

Please, when you do have an ETA, don't hesitate to let me know.

Best Regards!

**Comment by carrodher** [comment]
Sure, I agree it's a good feature to have in the container/chart but we are a small team with several requests, and unfortunately in some cases like this one it is not possible to accept external contributions since the piece of code that needs to be modified are not public yet.
In those cases, we need to evaluate internally according to other priorities the team has. I already created the internal task, now it should be evaluated by other people and prioritize depending on the bandwidth we have for the following weeks, that is the reason why I can't provide an ETA at this moment

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
