### ISSUE TITLE
[Feature Request] Maintain LTS version

### ISSUE THREAD

**Issue by sida-khalibre** [bitnami/bitnami-docker-moodle#182]
This is just a feature request for Bitnami to maintain the LTS version with the latest security update such as Moodle 3.9.

**Comment by miguelaeh** [comment]
Hi @sida-khalibre ,
Thank you very much for this feature request.
I checked the moodle docs and it seems that we are using as branch `3`, while we should be using `3.X`. I will discuss this with the team to evaluate if we should change it.

**Comment by sida-khalibre** [comment]
Thank @miguelaeh it would be great and helpful if Bitnami Moodle support LTS version.

**Comment by hercial61** [comment]
Sorry for the issue

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
