### ISSUE TITLE
address already in use

### ISSUE THREAD

**Issue by qceME** [bitnami/bitnami-docker-moodle#74]
How can i fix this error?:  Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

I have repeated the installation 5 times and i always receive the same error, why?
I dont know how fix it, im new using GCE and kubernetes, help please :(

**Comment by juan131** [comment]
Hi @qceME 

That error implies there's another process listening on the port 80. That's a common issue when deploying a container locally and trying to bind the port 80 (which can be occupied by another web server). 

However, you mentioned you deployed your Moodle solution on Kubernetes, that's vey weird. On K8s, Moodle should be running on a POD with just one container (the Moodle one), therefore, there shouldn't be any problem binding ports since there won't be any other process.

Did you obtain the error while trying to do a local proxy or port-forwarding? Sth like:

```
 kubectl port-forward YOUR-MOODLE-POD 8080:80
```

**Comment by qceME** [comment]
Gracias por responder Juan! Estoy con el proyecto final y me tiene loco esto, he conseguido levantar en GKE Wordpress pero Moodle nada, ahora mi aplicacion ya está accesible a internet pero me da el tipico error:
Error: Database connection failed

It is possible that the database is overloaded or otherwise not running properly.

The site administrator should also check that the database details have been correctly specified in config.php

Pero claro, al ir kubernetes con archivos manifiesto no tengo ni idea de como solucionar eso

**Comment by juan131** [comment]
Hi @qceME 

> Como hispanohablante, no me importa en absoluto responderle en castellano, pero preferiría que la respuesta fuera en inglés para maximizar la utilidad de esta respuesta. Si el lenguaje se convirtiera en una auténtica barrera para entenderme, hágamelo saber y pasaré completamente al castellano. Puede seguir usando el castellano, si así lo prefiere, para preguntar.

How are you deploying Moodle?
 - Did you use Helm to install Moodle on your GKE cluster? If so, did you change any parameter or are you using the default values? (see https://github.com/kubernetes/charts/tree/master/stable/moodle#configuration for more info)
 - Are you using your own manifests? Share them if so please.
