### ISSUE TITLE
Upgrade persistence

### ISSUE THREAD

**Issue by nevotheless** [bitnami/bitnami-docker-moodle#90]
Hello,

I wanted to get some Infos about the Intend of making the whole `/bitnami` folder persistent.

Because for a production Environment, this breaks proper upgrading of the whole Application.
On the readme, it's written that for the upgrade to succeed, the Volume needs to get removed. (I understand why.)

But why don't you persist the Data of Moodle that actually need to be persistent (e.g. moodle_data, mod, themes) instead of the whole applications?

I just want to understand why this approach was taken.

Would really appreciate an answer to understand this a whole lot better.

**Comment by alemorcuq** [comment]
Hi, @nevotheless.

I would need to revisit the context of the change because it was more than a year ago, but usually it's due to one of two reasons:

- The folder structure varies a lot between versions, making it difficult to maintain.
- Some files that should be persisted link to files that aren't persisted (like libraries). This breaks the functionality as persistence is done through symlinks.

Regards,
Alejandro

**Comment by nevotheless** [comment]
@alemorcuq  thanks for the answer.

I'm not a huge Moodle expert but I think changes are needed to make this viable for production usage. To just make `/bitnami` persistent defeats the purpose of adding any persistence at all, since it needs to get removed in order to upgrade the container.

Just as an example to further understand all this: Shouldn't folders like these ideally be made persistent instead:
 - `/bitnami/moodle/mod` (for plugins)
 - `/bitnami/moodle/theme`
 - `/bitnami/moodle/moodledata`

So that users can at least Upload Plugins, Use custom Themes and language Packs without losing them after upgrading?

**Comment by marcosbc** [comment]
Hi @nevotheless, Moodle was causing issues when we tried to implement persistence for those directories, because of how it was importing files.

The problem is that it in some cases internally relies on the PHP `__FILE__` and `__DIR__` variable, which resolves symlinks. Therefore, if you have a symlink like the following one:

    /bitnami/moodle/mod -> /opt/bitnami/moodle/mod

Then, scripts if you had a script like "mod/somescript.php" with the following contents:

    require_once(__DIR__ . '/../lib/somefile.php');

It would fail because `lib` is not persisted.

In any case, I have been able to get Moodle working by persisting those directories. It is possible I'm missing some feature, which is why we'll investigate a bit more and get to you with a more specific answer (i.e. with a specific error if only those directories are persisted).

**Comment by nevotheless** [comment]
Oh okay, yeah that makes sense. Sounds good. I guess you make the
respective folders in /opt persistent and restore the symlinks (if needed?
I Don't know how symlinkedwould behave) via a script or something else
then?

That's always my biggest issue as well, when it comes to containerize
applications... To find all the nooks and crannies that need to get
persisted, it's such a pain to figure that out.

For moodle I only see, mod, theme, moodledata and probably the config.php
at first glance.

Marcos Bjoerkelund <notifications@github.com> schrieb am Mi., 1. Mai 2019,
18:27:

**Comment by nevotheless** [comment]
Oh okay, yeah that makes sense. Sounds good. 

I guess you make the respective folders in /opt persistent and restore the symlinks (if needed? I Don't know how symlinkedwould behave) via a script or something else then?

 That's always my biggest issue as well, when it comes to containerize applications... To find all the nooks and crannies that need to get persisted, it's such a pain to figure that out. For moodle I only see, mod, theme, moodledata and probably the config.php at first glance.

**Comment by breyvilas** [comment]
@nevotheless Almost literally everything on the moodle folder should/can be persisted due to the way Moodle plugins work. If you install an authentication plugin, for example, it will be located in `moodle-dir/auth`, if it's a block plugin it will be in `moodle-dir/blocks`, etc.

**Comment by nevotheless** [comment]
Oh, that complicates proper life cycle design, I understand now. I guess my questions are answered then and I think that this won't be an adequate solution to work with, for me. 

Thanks for clarifying how all this works, though. 👍 ❤️

**Comment by marcosbc** [comment]
Hi @nevotheless, after further investigation, the main reason for not enabling persistence is because of all the possible locations plugins may be stored at. This is the page which describes the location for plugins: https://docs.moodle.org/dev/Plugin_types

The application does in fact seem to work, but the problem is the following directories would need to be persisted:

- mod
- lib/antivirus
- files/converter
- lib/mlbackend
- blocks
- question/type
- question/behaviour
- export
- filter
- lib/editor
- lib/editor/atto/plugins
- lib/editor/tinymce/plugins
- enrol
- auth
- admin/tool
- admin/tool/log/store
- availability/condition
- calendar/type
- message/output
- course/format
- dataformat
- user/profile/field
- report
- grade/export
- grade/import
- grade/report
- grade/grading/form
- mnet/service
- webservice
- repository
- portfolio
- search/engine
- media/player
- plagiarism
- cache/stores
- cache/locks
- theme
- local
- moodledata

As you can see it's a lot of directories, and some of them may change from one version to another. I'm not fully confident that we should change this to the way it was before, persisting only necessary directories, as it could cause a lot of trouble when updating.
