### ISSUE TITLE
Moodle 3.7+ vs 3.7 in container

### ISSUE THREAD

**Issue by sillyfrog** [bitnami/bitnami-docker-moodle#93]
More of a support/feature request than an issue. I'm new to Moodle, and this image, so please excuse me if I'm missing something obvious. Also, a thank-you for this image, it made getting started with Moodle super simple!

**Description**

I'm wanting to clarify the version of Moodle in the Docker image, best I can tell it's 3.7 (looking at /bitnami/moodle/version.php). Looking at the downloads page, they are now suggesting it's better to run v3.7+ in production (https://download.moodle.org/releases/latest/). My request is; are you able to make a release/tag that includes the 3.7+ release? I see that the docker image is built regularly, so hopefully it would be an easy step to include this as one of the builds.

I have had a quick look and putting in a PR, but most of the magic appears to be in the Bitnami scripts, and at this stage I don't have an understanding of how all of that ties together.

Thanks!

**Comment by carrodher** [comment]
Hi @sillyfrog, thanks for the suggestion. Currently, we are tracking the releases from the GitHub repository: https://github.com/moodle/moodle/releases. In this page, there are no references to the 3.7+ version as only the official update appears. We usually follow this workflow in order to detect new versions, in this specific case is not clear how the weekly releases work. Anyway, I just created an internal task in order to evaluate it.

Bitnami builds the images on a daily basis including system packages and components (apache, mysql, php, etc) updates, but we only release a new application version when it is released in upstream.

**Comment by sillyfrog** [comment]
I see the dilemma! Thanks for looking into this, much appreciated.
